In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sqlalchemy import create_engine

In [5]:
df = pd.read_csv("Luxury_Housing_Bangalore.csv")

In [6]:
df.head()

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292151871065954,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724412961911,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494232896,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392444511946,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.

##  DATA CLEANING :

In [7]:
df.isnull().sum()

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft          10046
Configuration               0
Ticket_Price_Cr         10019
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10090
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18287
dtype: int64

Filling the NAN data with median():

In [8]:
df["Unit_Size_Sqft"]

0         4025.0
1         5760.0
2         7707.0
3         6192.0
4         7147.0
           ...
100995    8546.0
100996    3408.0
100997    4691.0
100998    7435.0
100999    3218.0
Name: Unit_Size_Sqft, Length: 101000, dtype: float64

In [9]:
df["Unit_Size_Sqft"] = pd.to_numeric(df["Unit_Size_Sqft"])

In [10]:
df.loc[df["Unit_Size_Sqft"] <= 0, "Unit_Size_Sqft"] = None

In [11]:
df["Unit_Size_Sqft"] = df["Unit_Size_Sqft"].fillna(df["Unit_Size_Sqft"].median())

In [12]:
df.isnull().sum()

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft              0
Configuration               0
Ticket_Price_Cr         10019
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10090
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18287
dtype: int64

1.Assign it as string

In [13]:
df["Ticket_Price_Cr"] = df["Ticket_Price_Cr"].astype(str)

In [14]:
df["Ticket_Price_Cr"]

0         12.750846039118798
1         16.292151871065954
2         10.517724412961911
3          9.396367494232896
4         15.345392444511946
                 ...
100995     11.33081004147843
100996    10.829373158307602
100997    11.183303152058548
100998    10.914156376035923
100999             ₹13.27 Cr
Name: Ticket_Price_Cr, Length: 101000, dtype: object

2.Replace the str_values:

In [15]:
df["Ticket_Price_Cr"] = df["Ticket_Price_Cr"].str.replace("₹", "", regex=False)

In [16]:
df["Ticket_Price_Cr"] = df["Ticket_Price_Cr"].str.replace("Cr", "", regex=False)

In [17]:
df["Ticket_Price_Cr"] = df["Ticket_Price_Cr"].str.strip()

In [18]:
df["Ticket_Price_Cr"]

0         12.750846039118798
1         16.292151871065954
2         10.517724412961911
3          9.396367494232896
4         15.345392444511946
                 ...
100995     11.33081004147843
100996    10.829373158307602
100997    11.183303152058548
100998    10.914156376035923
100999                 13.27
Name: Ticket_Price_Cr, Length: 101000, dtype: object

Now I can change the error value:

In [19]:
df["Ticket_Price_Cr"] = pd.to_numeric(df["Ticket_Price_Cr"], errors='coerce')

In [20]:
df["Ticket_Price_Cr"] = df["Ticket_Price_Cr"].fillna(df["Ticket_Price_Cr"].median())

In [21]:
df.isnull().sum()

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft              0
Configuration               0
Ticket_Price_Cr             0
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score           10090
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18287
dtype: int64

In [22]:
df["Amenity_Score"] = df["Amenity_Score"].fillna(df["Amenity_Score"].median())

In [23]:
df.isnull().sum()

Property_ID                 0
Micro_Market                0
Project_Name                0
Developer_Name              0
Unit_Size_Sqft              0
Configuration               0
Ticket_Price_Cr             0
Transaction_Type            0
Buyer_Type                  0
Purchase_Quarter            0
Connectivity_Score          0
Amenity_Score               0
Possession_Status           0
Sales_Channel               0
NRI_Buyer                   0
Locality_Infra_Score        0
Avg_Traffic_Time_Min        0
Buyer_Comments          18287
dtype: int64

In [24]:
df = df.drop("Buyer_Comments", axis=1)

In [25]:
df.isnull().sum()

Property_ID             0
Micro_Market            0
Project_Name            0
Developer_Name          0
Unit_Size_Sqft          0
Configuration           0
Ticket_Price_Cr         0
Transaction_Type        0
Buyer_Type              0
Purchase_Quarter        0
Connectivity_Score      0
Amenity_Score           0
Possession_Status       0
Sales_Channel           0
NRI_Buyer               0
Locality_Infra_Score    0
Avg_Traffic_Time_Min    0
dtype: int64

change "Configuration" str_value in same format:

In [26]:
df["Configuration"]

0          4bhk
1          3Bhk
2          4bhk
3          3BHK
4          4Bhk
          ...
100995    5Bhk+
100996     3bhk
100997     4BHK
100998     3BHK
100999     4bhk
Name: Configuration, Length: 101000, dtype: object

In [27]:
df["Configuration"] = df["Configuration"].str.strip().str.upper()

In [28]:
df["Configuration"]

0          4BHK
1          3BHK
2          4BHK
3          3BHK
4          4BHK
          ...
100995    5BHK+
100996     3BHK
100997     4BHK
100998     3BHK
100999     4BHK
Name: Configuration, Length: 101000, dtype: object

Developer Name normalize

Normalize text fields

In [29]:
df["Developer_Name"].head(10)

0                  RMZ
1          Puravankara
2         Tata Housing
3              Embassy
4              SNN Raj
5              Brigade
6             Prestige
7    Total Environment
8             Prestige
9          Puravankara
Name: Developer_Name, dtype: object

Change the text format as Capt"

In [30]:
df["Developer_Name"] = df["Developer_Name"].str.strip().str.upper()

In [31]:
df["Developer_Name"].head(10)

0                  RMZ
1          PURAVANKARA
2         TATA HOUSING
3              EMBASSY
4              SNN RAJ
5              BRIGADE
6             PRESTIGE
7    TOTAL ENVIRONMENT
8             PRESTIGE
9          PURAVANKARA
Name: Developer_Name, dtype: object

In [32]:
df["Micro_Market"] = df["Micro_Market"].str.strip().str.upper()

In [33]:
df["Micro_Market"]

0             SARJAPUR ROAD
1               INDIRANAGAR
2         BANNERGHATTA ROAD
3              BELLARY ROAD
4               KORAMANGALA
                ...
100995         BELLARY ROAD
100996         BELLARY ROAD
100997          HENNUR ROAD
100998          RAJAJINAGAR
100999           WHITEFIELD
Name: Micro_Market, Length: 101000, dtype: object

In [34]:
df.columns

Index(['Property_ID', 'Micro_Market', 'Project_Name', 'Developer_Name',
       'Unit_Size_Sqft', 'Configuration', 'Ticket_Price_Cr',
       'Transaction_Type', 'Buyer_Type', 'Purchase_Quarter',
       'Connectivity_Score', 'Amenity_Score', 'Possession_Status',
       'Sales_Channel', 'NRI_Buyer', 'Locality_Infra_Score',
       'Avg_Traffic_Time_Min'],
      dtype='object')

# Feature Engineering

Price_per_Sqft :

In [35]:
df["Price_per_Sqft"] = (df["Ticket_Price_Cr"] * 10000000) / df["Unit_Size_Sqft"]

In [ ]:
df["Price_per_Sqft"]

0         31679.120594
1         28284.985887
2         13646.976013
3         15175.012103
4         21471.096187
              ...
100995    13258.612265
100996    31776.329690
100997    23839.912923
100998    14679.430230
100999    41236.793039
Name: Price_per_Sqft, Length: 101000, dtype: float64

In [36]:
df[["Ticket_Price_Cr", "Unit_Size_Sqft", "Price_per_Sqft"]].head()

   Ticket_Price_Cr  Unit_Size_Sqft  Price_per_Sqft
0        12.750846          4025.0    31679.120594
1        16.292152          5760.0    28284.985887
2        10.517724          7707.0    13646.976013
3         9.396367          6192.0    15175.012103
4        15.345392          7147.0    21471.096187

Quarter_Numbers:

Convert Purchase_Quarter to date

In [37]:
df["Purchase_Quarter"] = pd.to_datetime(df["Purchase_Quarter"])

Extract Quarter_Number

In [38]:
df["Quarter_Number"] = df["Purchase_Quarter"].dt.quarter

Booking_Flag:

Create Booking Flag

In [39]:
df["Booking_Flag"] = df["Transaction_Type"].map({"Primary": 1, "Secondary": 0})

In [40]:
df[["Price_per_Sqft", "Quarter_Number", "Booking_Flag"]].head()

   Price_per_Sqft  Quarter_Number  Booking_Flag
0    31679.120594               1             1
1    28284.985887               2             1
2    13646.976013               4             1
3    15175.012103               1             1
4    21471.096187               4             0

In [41]:
df.columns

Index(['Property_ID', 'Micro_Market', 'Project_Name', 'Developer_Name',
       'Unit_Size_Sqft', 'Configuration', 'Ticket_Price_Cr',
       'Transaction_Type', 'Buyer_Type', 'Purchase_Quarter',
       'Connectivity_Score', 'Amenity_Score', 'Possession_Status',
       'Sales_Channel', 'NRI_Buyer', 'Locality_Infra_Score',
       'Avg_Traffic_Time_Min', 'Price_per_Sqft', 'Quarter_Number',
       'Booking_Flag'],
      dtype='object')

In [42]:
df[["Price_per_Sqft", "Quarter_Number", "Booking_Flag"]].isnull().sum()

Price_per_Sqft    0
Quarter_Number    0
Booking_Flag      0
dtype: int64

In [43]:
engine = create_engine("postgresql+psycopg2://postgres:Karan7826@localhost:5432/luxury_db")

In [44]:
df.to_sql("luxury_house_sale", con=engine, if_exists="replace", index=False)

1000

In [45]:
pd.read_sql('SELECT "Price_per_Sqft", "Booking_Flag" FROM luxury_house_sale LIMIT 5;', engine)

   Price_per_Sqft  Booking_Flag
0    31679.120594             1
1    28284.985887             1
2    13646.976013             1
3    15175.012103             1
4    21471.096187             0

In [46]:
pd.read_sql('SELECT "Price_per_Sqft" FROM luxury_house_sale LIMIT 10;', engine)

   Price_per_Sqft
0    31679.120594
1    28284.985887
2    13646.976013
3    15175.012103
4    21471.096187
5    22890.442890
6    16081.393675
7    16237.270421
8    21151.245761
9    10597.475826

Create DB connection:

In [47]:
engine = create_engine("postgresql+psycopg2://postgres:Karan7826@localhost:5432/luxury_db")

In [48]:
df.to_sql("luxury_house_sale", con=engine, if_exists="replace", index=False)

1000

In [49]:
pd.read_sql('SELECT AVG("Price_per_Sqft") AS avg_price FROM luxury_house_sale;', engine)

      avg_price
0  22914.623457

# Count how many negative rows exist

In [50]:
pd.read_sql('SELECT COUNT(*) AS negative_count FROM luxury_house_sale WHERE "Price_per_Sqft" < 0;', engine)

   negative_count
0               5

# Find what those bad rows look like

In [51]:
pd.read_sql('SELECT "Ticket_Price_Cr", "Unit_Size_Sqft", "Price_per_Sqft" FROM luxury_house_sale WHERE "Price_per_Sqft" < 0;', engine)

   Ticket_Price_Cr  Unit_Size_Sqft  Price_per_Sqft
0        -0.391623          5092.0     -769.093841
1        -1.420000          4019.0    -3533.217218
2        -0.287197          4924.0     -583.260311
3        -0.193873          5807.0     -333.860845
4        -0.519437          6548.0     -793.275119