In [61]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sqlalchemy import create_engine

Load cleaned CSV file:

In [62]:
df = pd.read_csv("cleaned_luxury_housing.csv")

In [63]:
df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Price_per_Sqft,Quarter_Number,Booking_Flag
0,PROP000001,SARJAPUR ROAD,Project_0,RMZ,4025.0,4BHK,12.750846,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,31679.120594,1,1
1,PROP000002,INDIRANAGAR,Project_1,PURAVANKARA,5760.0,3BHK,16.292152,Primary,Other,2024-06-30,4.839024,7.499123,Under construction,NRI Desk,no,7.723898,106,28284.985887,2,1
2,PROP000003,BANNERGHATTA ROAD,Project_2,TATA HOUSING,7707.0,4BHK,10.517724,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,13646.976013,4,1
3,PROP000004,BELLARY ROAD,Project_3,EMBASSY,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,15175.012103,1,1
4,PROP000005,KORAMANGALA,Project_4,SNN RAJ,7147.0,4BHK,15.345392,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,21471.096187,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,BELLARY ROAD,Project_229,EMBASSY,8546.0,5BHK+,11.330810,Secondary,CXO,2024-12-31,8.552797,6.221131,Under construction,NRI Desk,no,7.511827,22,13258.612265,4,0
100996,PROP059810,BELLARY ROAD,Project_309,BRIGADE,3408.0,3BHK,10.829373,Primary,CXO,2024-09-30,6.879269,9.783611,Ready to move,Direct,no,9.851849,26,31776.329690,3,1
100997,PROP065099,HENNUR ROAD,Project_98,RMZ,4691.0,4BHK,11.183303,Primary,NRI,2023-12-31,6.753812,8.383013,Under construction,Broker,no,9.101604,44,23839.912923,4,1
100998,PROP093022,RAJAJINAGAR,Project_21,EMBASSY,7435.0,3BHK,10.914156,Secondary,Other,2024-06-30,4.437787,5.756247,Under construction,Broker,yes,8.588551,66,14679.430230,2,0
100999,PROP023826,WHITEFIELD,Project_325,L&T REALTY,3218.0,4BHK,13.270000,Primary,Startup Founder,2023-12-31,7.760416,9.989290,Under construction,Direct,yes,9.917647,58,41236.793039,4,1

Create DB connection:

In [64]:
engine = create_engine("postgresql+psycopg2://postgres:Karan7826@localhost:5432/luxury_db")

In [65]:
df.to_sql("luxury_house", con=engine, if_exists="replace", index=False)

1000

In [66]:
pd.read_sql('SELECT "Transaction_Type", "Booking_Flag" FROM luxury_house LIMIT 10;', engine)

  Transaction_Type  Booking_Flag
0          Primary             1
1          Primary             1
2          Primary             1
3          Primary             1
4        Secondary             0
5        Secondary             0
6        Secondary             0
7        Secondary             0
8        Secondary             0
9          Primary             1

In [67]:
pd.read_sql("SELECT * FROM luxury_house LIMIT 10;", engine)

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Price_per_Sqft,Quarter_Number,Booking_Flag
0,PROP000001,SARJAPUR ROAD,Project_0,RMZ,4025.0,4BHK,12.750846,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,31679.120594,1,1
1,PROP000002,INDIRANAGAR,Project_1,PURAVANKARA,5760.0,3BHK,16.292152,Primary,Other,2024-06-30,4.839024,7.499123,Under construction,NRI Desk,no,7.723898,106,28284.985887,2,1
2,PROP000003,BANNERGHATTA ROAD,Project_2,TATA HOUSING,7707.0,4BHK,10.517724,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,13646.976013,4,1
3,PROP000004,BELLARY ROAD,Project_3,EMBASSY,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,15175.012103,1,1
4,PROP000005,KORAMANGALA,Project_4,SNN RAJ,7147.0,4BHK,15.345392,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,21471.096187,4,0
5,PROP000006,YELAHANKA,Project_5,BRIGADE,4290.0,4BHK,9.820000,Secondary,HNI,2023-09-30,7.936068,7.499123,Launch,Online,no,5.154027,16,22890.442890,3,0
6,PROP000007,BANNERGHATTA ROAD,Project_6,PRESTIGE,6776.0,5BHK+,10.896752,Secondary,Other,2025-03-31,8.643117,8.355238,Under construction,Direct,no,9.791550,74,16081.393675,1,0
7,PROP000008,WHITEFIELD,Project_7,TOTAL ENVIRONMENT,5763.0,3BHK,9.357539,Secondary,NRI,2025-03-31,6.781306,9.565013,Under construction,Direct,yes,9.054713,31,16237.270421,1,0
8,PROP000009,SARJAPUR ROAD,Project_8,PRESTIGE,5815.0,3BHK,12.299449,Secondary,Other,2024-03-31,7.284164,5.580442,Under construction,NRI Desk,yes,8.552046,68,21151.245761,1,0
9,PROP000010,JP NAGAR,Project_9,PURAVANKARA,8675.0,4BHK,9.193310,Primary,CXO,2023-09-30,9.964399,7.759907,Launch,Direct,yes,8.395691,18,10597.475826,3,1

In [68]:
pd.read_sql("""
SELECT "Micro_Market", 
AVG("Ticket_Price_Cr") AS avg_price
FROM luxury_house
GROUP BY "Micro_Market"
ORDER BY avg_price DESC
LIMIT 10;
""", engine)

        Micro_Market  avg_price
0      SARJAPUR ROAD  12.835822
1             HEBBAL  12.780053
2        HENNUR ROAD  12.682557
3  BANNERGHATTA ROAD  12.677015
4            MG ROAD  12.673694
5        KORAMANGALA  12.673545
6          JAYANAGAR  12.660273
7           JP NAGAR  12.651805
8          YELAHANKA  12.632407
9        INDIRANAGAR  12.616555

In [69]:
pd.read_sql("""
SELECT "Developer_Name", 
AVG("Ticket_Price_Cr") AS avg_price
FROM luxury_house
GROUP BY "Developer_Name"
ORDER BY avg_price DESC
LIMIT 10;
""", engine)

      Developer_Name  avg_price
0              SOBHA  12.796678
1  TOTAL ENVIRONMENT  12.747614
2         L&T REALTY  12.712636
3             GODREJ  12.688487
4                RMZ  12.671626
5        PURAVANKARA  12.665814
6           PRESTIGE  12.643322
7       TATA HOUSING  12.604211
8            SNN RAJ  12.549005
9            BRIGADE  12.544106

In [70]:
pd.read_sql("""
SELECT "Configuration", 
AVG("Price_per_Sqft") AS avg_price_sqft
FROM luxury_house
GROUP BY "Configuration"
ORDER BY avg_price_sqft DESC;
""", engine)

  Configuration  avg_price_sqft
0         5BHK+  -568102.536298
1          4BHK  -598119.587560
2          3BHK  -659583.704479

In [71]:
pd.read_sql("""
SELECT "Quarter_Number", 
COUNT(*) AS total_properties
FROM luxury_house
GROUP BY "Quarter_Number"
ORDER BY "Quarter_Number";
""", engine)

   Quarter_Number  total_properties
0               1             25281
1               2             25263
2               3             25301
3               4             25155

In [72]:
pd.read_sql("""
SELECT "Transaction_Type", 
COUNT(*) AS count
FROM luxury_house
GROUP BY "Transaction_Type";
""", engine)

  Transaction_Type  count
0          Primary  50494
1        Secondary  50506

In [73]:
pd.read_sql("SELECT * FROM luxury_house LIMIT 5;", engine)

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Price_per_Sqft,Quarter_Number,Booking_Flag
0,PROP000001,SARJAPUR ROAD,Project_0,RMZ,4025.0,4BHK,12.750846,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,31679.120594,1,1
1,PROP000002,INDIRANAGAR,Project_1,PURAVANKARA,5760.0,3BHK,16.292152,Primary,Other,2024-06-30,4.839024,7.499123,Under construction,NRI Desk,no,7.723898,106,28284.985887,2,1
2,PROP000003,BANNERGHATTA ROAD,Project_2,TATA HOUSING,7707.0,4BHK,10.517724,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,13646.976013,4,1
3,PROP000004,BELLARY ROAD,Project_3,EMBASSY,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,15175.012103,1,1
4,PROP000005,KORAMANGALA,Project_4,SNN RAJ,7147.0,4BHK,15.345392,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,21471.096187,4,0

In [74]:
pd.read_sql("SELECT * FROM luxury_house LIMIT 5;", engine)

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Price_per_Sqft,Quarter_Number,Booking_Flag
0,PROP000001,SARJAPUR ROAD,Project_0,RMZ,4025.0,4BHK,12.750846,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,31679.120594,1,1
1,PROP000002,INDIRANAGAR,Project_1,PURAVANKARA,5760.0,3BHK,16.292152,Primary,Other,2024-06-30,4.839024,7.499123,Under construction,NRI Desk,no,7.723898,106,28284.985887,2,1
2,PROP000003,BANNERGHATTA ROAD,Project_2,TATA HOUSING,7707.0,4BHK,10.517724,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,13646.976013,4,1
3,PROP000004,BELLARY ROAD,Project_3,EMBASSY,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,15175.012103,1,1
4,PROP000005,KORAMANGALA,Project_4,SNN RAJ,7147.0,4BHK,15.345392,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,21471.096187,4,0

In [75]:
df["Booking_Flags"] = df["Transaction_Type"].map({"Primary": 1, "Secondary": 0})

In [76]:
pd.read_sql('SELECT "Booking_Flag" FROM luxury_house LIMIT 5;', engine)

   Booking_Flag
0             1
1             1
2             1
3             1
4             0

In [77]:
pd.read_sql("""
SELECT column_name
FROM information_schema.columns
WHERE table_name = 'luxury_house';
""", engine)

             column_name
0           Booking_Flag
1         Unit_Size_Sqft
2        Ticket_Price_Cr
3     Connectivity_Score
4          Amenity_Score
5   Locality_Infra_Score
6   Avg_Traffic_Time_Min
7         Price_per_Sqft
8         Quarter_Number
9       Purchase_Quarter
10             NRI_Buyer
11           Property_ID
12          Micro_Market
13          Project_Name
14        Developer_Name
15     Possession_Status
16         Configuration
17         Sales_Channel
18      Transaction_Type
19            Buyer_Type

In [78]:
pd.read_sql('SELECT "Transaction_Type", "Booking_Flag" FROM luxury_house LIMIT 10;', engine)

  Transaction_Type  Booking_Flag
0          Primary             1
1          Primary             1
2          Primary             1
3          Primary             1
4        Secondary             0
5        Secondary             0
6        Secondary             0
7        Secondary             0
8        Secondary             0
9          Primary             1

Upload data to PostgreSQL: